### ISSUE TITLE
[FEATURE] Form params expectation 

### ISSUE THREAD

**Issue by satoved** [blastcloud/guzzler#1]
Is there a way to assert against
```
['form_params' => ['a' => 'b']]
```
requests?

**Comment by satoved** [comment]
Maybe a shorthand for
```
->withBody(http_build_query($body, '', '&'))
```

**Comment by adamkelso** [comment]
There's not currently, but that's a great idea. How does this API look to you?

```php
// For individual fields
$expect->withFormField($field, $value);

// For several fields
$expect->withForm([
    'field' => $value,
    // ...
);
```

If that looks good, would it also make sense to you to allow an 'exclusive' boolean that works in the same way as **withQuery**?

**Comment by satoved** [comment]
API looks great!

Personally I've never needed exclusive assertion, but there could be cases for this possible.

A json syntax sugar could be nice too

```
$expect->withJson(array $json);
```

instead of

```
->withBody(json_encode($json))
```

Thanks for the package, testing APIs became so easy with it!

**Comment by adamkelso** [comment]
😃 You made my day. I'm glad it's been helpful.

I just made a new release - 1.2.0 - that adds all three methods discussed above.

[withJson()](https://guzzler.dev/expectations/#withjson)
[withFormField()](https://guzzler.dev/expectations/#withformfield-string-key-value)
[withForm()](https://guzzler.dev/expectations/#withform-array-formfields)

**Comment by adamkelso** [comment]
Just as an update for anyone who comes to this, all three of these methods were updated in release `1.2.1`. 

- Both form methods now handle both URL encoded and multipart forms.
- The `withJson` method now ensures the passed argument appears in the JSON body somewhere, but does not require an exact match. But an exact match can be forced with a boolean `true` as the second argument.
