### ISSUE TITLE
Error: Cannot instantiate interface PHPUnit\Framework\MockObject\Invocation

### ISSUE THREAD

**Issue by antonhedling** [blastcloud/guzzler#11]
Hello, just discovered this package and it looks incredible. However I am having some issues, can't seem to locate the issue.

Sample code:
```
$this->guzzler->expects($this->once())
            ->get('/v2/balance')
            ->willRespond(new Response(401, [], '{}'));
```
            
Error:
```
Error: Cannot instantiate interface PHPUnit\Framework\MockObject\Invocation

/Users/anton/Projects/project/project/vendor/blastcloud/chassis/src/Expectation.php:119
/Users/anton/Projects/project/project/vendor/blastcloud/chassis/src/Chassis.php:33
/Users/anton/Projects/project/project/vendor/blastcloud/guzzler/src/UsesGuzzler.php:37
/Users/anton/Projects/project/project/vendor/blastcloud/guzzler/src/UsesGuzzler.php:3
```

PHPUnit Version: **9.5.1**
Guzzle Version: **7.2**
Guzzler Version: **2.0.1**
PHP Version: **7.4**

Any ideas?

**Comment by antonhedling** [comment]
Okay, don't be an idiot like me. While I had PHPUnit 9 in the vendor/ folder, running 'phpunit' in my terminal used a global PHPUnit installation at 7.5 instead. Issues no longer remain.

**Comment by adamkelso** [comment]
Hey @antonhedling . No worries. I’ve done plenty of things like that before. And thanks for the complements. I’m really glad you like the library.
