### ISSUE TITLE
document source

### ISSUE THREAD

**Issue by alighasemzadeh** [blastcloud/guzzler#2]
Hello,
Can we have access to document source?

**Comment by adamkelso** [comment]
The [documentation]()https://github.com/blastcloud/guzzler-docs is public.

**Comment by alighasemzadeh** [comment]
@adamkelso 
Which UI do you use?

**Comment by adamkelso** [comment]
Sorry, I guess I should explain in the readme on that project. It's built in [Vuepress](https://vuepress.vuejs.org/). All the text on each page are located in the `docs` directory, and all configuration is in the `docs/.vuepress` directory.

If you'd like to build it locally, do the following:

1. Clone the repo
2. Install the dependencies via either Yarn or NPM. (Example: `yarn install`).
3. Run the dev for hot-swapping. `yarn docs:dev`.

You can also fully build the results with `yarn docs:build`.

**Comment by adamkelso** [comment]
I'm going to mark this closed for now. If you have any further questions to ask, feel free to post them on the docs project.
